-- Initial market catalog seed for CLI migrations.
-- Safe to apply to an existing database: existing external_id rows are preserved.
-- All imported rows remain needs_review until independently verified.
-- Generated from public/data/night-markets.json.
-- Candidates remain needs_review until independently checked.
insert into public.markets (external_id, name, city, district, address, latitude, longitude, status, source_url, source_date) values
('tw-tpe-raohestreet', '饒河街觀光夜市', '臺北市', '松山區', '臺北市松山區饒河街', 25.05068, 121.57507, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('tw-tpe-nanjichang', '南機場夜市', '臺北市', '中正區', null, null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('tw-newtaipei-banqiao', '板橋湳雅夜市', '新北市', '板橋區', null, null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('tw-newtaipei-lehua', '樂華攤集區（觀光夜市）', '新北市', '永和區', null, null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('tw-newtaipei-xinren', '興仁花園夜市', '新北市', '樹林區', null, null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('tw-taoyuan-zhongli', '中壢觀光夜市', '桃園市', '中壢區', '桃園市中壢區新明國小（中央西路二段 97 號）旁', 24.9605, 121.2158, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('tw-taoyuan-zhongyuan', '中原夜市', '桃園市', '中壢區', '桃園市中壢區實踐路、日新路（中原大學周邊）', 24.95545, 121.24061, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('tw-taoyuan-taoyuan', '桃園觀光夜市', '桃園市', '桃園區', '桃園市桃園區', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('tw-taoyuan-longtan', '龍潭觀光夜市', '桃園市', '龍潭區', '桃園市龍潭區', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('tw-taoyuan-xingren', '興仁花園夜市', '桃園市', '八德區', '桃園市八德區', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('tw-tx-dajia', '大甲蔣公路觀光夜市', '臺中市', '大甲區', null, null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('tw-tx-fengjia', '逢甲觀光夜市攤販集中區', '臺中市', '西屯區', null, null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('tw-tx-huangxi', '旱溪夜市攤販集中區', '臺中市', '東區', null, null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('tw-tainan-fuhua', '復華夜市', '臺南市', '永康區', null, null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('tw-tainan-wusheng', '武聖夜市', '臺南市', '中西區', null, null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('tw-hualien-dongdamen', '東大門福町夜市', '花蓮縣', '花蓮市', null, null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('tw-hualien-ziqiang', '東大門自強夜市', '花蓮縣', '花蓮市', null, null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('tw-taitung-tourist', '臺東市觀光夜市', '臺東縣', '臺東市', null, null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-001-基隆市-八斗子夜市', '八斗子夜市', '基隆市', '中正區', '北寧路217號旁空地', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-002-基隆市-基金一路夜市', '基金一路夜市', '基隆市', '安樂區', '基金一路129巷空地', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-003-基隆市-愛四路夜市', '愛四路夜市', '基隆市', '仁愛區', '愛四路（仁一路至仁三路間）', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-004-基隆市-廟口', '廟口', '基隆市', '仁愛區', '仁三路（愛三路至愛四路）', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-005-臺北市-饒河街臨時攤販集中場', '饒河街臨時攤販集中場', '臺北市', '松山區', '臺北市松山區饒河街', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-006-臺北市-臨江街臨時攤販集中場', '臨江街臨時攤販集中場', '臺北市', '大安區', '臺北市大安區臨江街(通化街至基隆路口)', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-007-臺北市-遼寧街臨時攤販集中場', '遼寧街臨時攤販集中場', '臺北市', '中山區', '臺北市中山區遼寧街(長安東路至朱崙街口,近朱崙公園)', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-008-臺北市-雙城街臨時攤販集中場', '雙城街臨時攤販集中場', '臺北市', '中山區', '臺北市中山區雙城街(雙城街10巷、13巷至農安街口,近晴光公園)', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-009-臺北市-華西街臨時攤販集中場', '華西街臨時攤販集中場', '臺北市', '萬華區', '臺北市萬華區華西街', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-010-臺北市-梧州街臨時攤販集中場', '梧州街臨時攤販集中場', '臺北市', '萬華區', '臺北市萬華區梧州街', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-011-臺北市-廣州街臨時攤販集中場', '廣州街臨時攤販集中場', '臺北市', '萬華區', '臺北市萬華區廣州街', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-012-臺北市-西昌街臨時攤販集中場', '西昌街臨時攤販集中場', '臺北市', '萬華區', '臺北市萬華區西昌街（廣州街至桂林路間）', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-013-臺北市-南機場臨時攤販集中場', '南機場臨時攤販集中場', '臺北市', '中正區', '臺北市中正區中華路二段307巷至315巷之易牙巷', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-014-臺北市-寧夏路臨時攤販集中場', '寧夏路臨時攤販集中場', '臺北市', '大同區', '臺北市大同區寧夏路', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-015-臺北市-延三臨時攤販集中場', '延三臨時攤販集中場', '臺北市', '大同區', '臺北市大同區延平北路三段 (民權西路至民族西路口)', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-017-新北市-興仁夜市', '興仁夜市', '新北市', '樹林區', '樹林區保安街2段68號旁', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-018-新北市-樂華觀光夜市', '樂華觀光夜市', '新北市', '永和區', '永和區永平路一段(永和路及中山路間)', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-019-新北市-觀光夜市', '觀光夜市', '新北市', '汐止區', '新北市汐止區水源路一段至新興路之台鐵橋下', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-022-苗栗縣-三義鄉休閒文化生活圈', '三義鄉休閒文化生活圈', '苗栗縣', '三義鄉', '三義鄉水尾溪河川加蓋停車場及周邊區域(三義鄉廣盛村)', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-023-苗栗縣-苗栗英才觀光夜市', '苗栗英才觀光夜市', '苗栗縣', '苗栗市', '苗栗市英才路與正發路交叉口', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-025-臺中市-環中夜市攤販集中區', '環中夜市攤販集中區', '臺中市', '西屯區', '西屯區環中路三段780-3號', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-026-臺中市-大甲蔣公路觀光夜市攤販集中區', '大甲蔣公路觀光夜市攤販集中區', '臺中市', '大甲區', '大甲區蔣公路段', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-027-臺中市-昌平夜市攤販集中區', '昌平夜市攤販集中區', '臺中市', '北屯區', '北屯區昌平路一段與北平路四段', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-029-臺中市-中華路觀光夜市攤販集中區', '中華路觀光夜市攤販集中區', '臺中市', '中區', '中區中華路一段、二段、公園路、大誠街路段及西屯區大鵬路與長安路二段', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-030-南投縣-三和夜市', '三和夜市', '南投縣', '南投市', '公園南街、大同街、三和二路、三和三路', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-031-南投縣-內興里夜市', '內興里夜市', '南投縣', '南投市', '內興路', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-032-南投縣-祖祠路夜市', '祖祠路夜市', '南投縣', '南投市', '祖祠東路6號前空地', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-033-南投縣-成功夜市', '成功夜市', '南投縣', '南投市', '成功二路及自強一路交叉口', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-034-南投縣-魚市場夜市', '魚市場夜市', '南投縣', '埔里鎮', '埔里鎮南盛街88號', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-035-南投縣-草鞋墩人文觀光夜市', '草鞋墩人文觀光夜市', '南投縣', '草屯鎮', '草屯鎮中正路1039號', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-036-南投縣-中寮夜市', '中寮夜市', '南投縣', '中寮鄉', '中寮鄉永安街與初中巷交叉路口', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-037-雲林縣-斗南鎮中興夜市', '斗南鎮中興夜市', '雲林縣', '斗南鎮', '雲林縣斗南鎮明昌中興段', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-038-嘉義市-文化路設攤區路段', '文化路設攤區路段', '嘉義市', '待補', '自中正路口退縮十公尺處起至垂楊路口退縮十公尺處止。各路口紅線區除外', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-039-臺南市-中興夜市', '中興夜市', '臺南市', '永康區', '臺南市永康區中華二路', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-040-臺南市-佳里傳統夜市', '佳里傳統夜市', '臺南市', '佳里區', '臺南市佳里區忠仁里與平等街上', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-041-臺南市-新市傳統夜市', '新市傳統夜市', '臺南市', '新市區', '臺南市新市區華興街與勝利街', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-042-臺南市-禹帝宮鹽行夜市', '禹帝宮鹽行夜市', '臺南市', '永康區', '臺南市永康區鹽行路、鹽洲一街', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-043-臺南市-鍾厝夜市', '鍾厝夜市', '臺南市', '仁德區', '臺南市仁德區中清路、仁義三街、仁義一街', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-044-臺南市-後壁厝夜市', '後壁厝夜市', '臺南市', '仁德區', '臺南市仁德區德南路', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-045-臺南市-長安路夜市', '長安路夜市', '臺南市', '白河區', '臺南市白河區光華路、長安路', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-046-臺南市-學甲傳統夜市', '學甲傳統夜市', '臺南市', '學甲區', '臺南市學甲區建國路', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-047-高雄市-六合二路', '六合二路', '高雄市', '新興區', '新興區中山一路至自立路', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-048-高雄市-南華路', '南華路', '高雄市', '新興區', '新興區中山三路至大同一路', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-049-高雄市-忠孝二路', '忠孝二路', '高雄市', '苓雅區', '苓雅區青年一路至苓雅一路', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-050-高雄市-興中路', '興中路', '高雄市', '苓雅區', '苓雅區興中一路(文橫二路)', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-051-高雄市-光華二路', '光華二路', '高雄市', '苓雅區', '苓雅區光華二路(三多二路至廣西路)', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-052-高雄市-自強三路', '自強三路', '高雄市', '苓雅區', '苓雅區自強三路(苓雅二路至興中二路)', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-053-高雄市-林靖', '林靖', '高雄市', '苓雅區', '苓雅區河南、河北、三多一路', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-054-高雄市-喜峰街', '喜峰街', '高雄市', '三民區', '三民區喜峰街(哈爾濱街至嫩江街)', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-055-高雄市-保安宮', '保安宮', '高雄市', '三民區', '三民區十全一路(保安宮前廣場)', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-056-高雄市-三民街', '三民街', '高雄市', '三民區', '三民區中華三路至自強一路', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-057-高雄市-前鎮加油站', '前鎮加油站', '高雄市', '前鎮區', '前鎮區前鎮里擴建一路', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-058-高雄市-凱旋青年', '凱旋青年', '高雄市', '前鎮區', '前鎮區凱旋四路758號', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-059-高雄市-左營大戲院', '左營大戲院', '高雄市', '左營區', '左營區大戲院後面空地', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-060-高雄市-第四攤集場(鹽埕街)', '第四攤集場(鹽埕街)', '高雄市', '鹽埕區', '鹽埕區大公路至富野路', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-061-高雄市-興達港', '興達港', '高雄市', '茄萣區', '茄萣區興達港大發路上', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-062-高雄市-蚵仔寮', '蚵仔寮', '高雄市', '梓官區', '梓官區漁港一路、漁港二路東側、港九街', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-063-屏東縣-瑞光夜市', '瑞光夜市', '屏東縣', '屏東市', '屏東市瑞光路三段、華正路', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-064-宜蘭縣-東門觀光夜市', '東門觀光夜市', '宜蘭縣', '宜蘭市', '宜蘭市聖後街31號', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-065-宜蘭縣-清溝夜市', '清溝夜市', '宜蘭縣', '冬山鄉', '清溝路之光明路至永興路段', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-066-宜蘭縣-太和夜市', '太和夜市', '宜蘭縣', '冬山鄉', '上河路義成橋至太安橋路段', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-067-宜蘭縣-羅東觀光夜市', '羅東觀光夜市', '宜蘭縣', '羅東鎮', '宜蘭羅東中山公園三周圍', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-068-宜蘭縣-三星運動場夜市', '三星運動場夜市', '宜蘭縣', '三星', '三星運動場', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-069-花蓮縣-花蓮東大門夜市', '花蓮東大門夜市', '花蓮縣', '花蓮市', '花蓮縣花蓮市重慶路572號', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-070-花蓮縣-鳳光夜市', '鳳光夜市', '花蓮縣', '鳳林鎮', '花蓮縣鳳林鎮中華路', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-071-花蓮縣-瑞穗週二夜市', '瑞穗週二夜市', '花蓮縣', '瑞穗鄉', '瑞穗鄉瑞美村中強路', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-072-臺東縣-台東觀光夜市', '台東觀光夜市', '臺東縣', '臺東市', '台東縣台東市正氣路段', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null),
('snapshot-073-臺東縣-四維夜市', '四維夜市', '臺東縣', '臺東市', '台東縣台東市四維路段', null, null, 'needs_review', 'https://data.gov.tw/dataset/95760', null)
on conflict (external_id) do nothing;
